### ISSUE TITLE
there's electionleaflet.org and electionleaflets.org?

### ISSUE THREAD

**Issue by annapowellsmith** [electionleaflets/electionleaflets#23]
which is the definitive site?

also, which is the definitive repo?

**Comment by rossjones** [comment]
@symroe'll know, but I __think__ he's developing on electionleaflet.org before moving it across.

**Comment by symroe** [comment]
Yep, it's more confusing that I anticipated! 

I got electionleaflet.org because it was free, and we want to use `#electionleaflet` as a hashtag for sharing things, so I thought peple might mistyope the domain name.

Because it was hanging about not doing anything, I thought I could use it for the staging dev version of the new site.

I really should have put it on dev.electionleaflet.org or something, to make it clear.

Still, hopefully we'll deploy the new version soon.

Also, I'm pushing to https://github.com/DemocracyClub/electionleaflets at the moment, and deploying from there.

**Comment by annapowellsmith** [comment]
ah thanks for the explanation... so will you redirect electionleaflets.org to electionleaflet.org at some point?

**Comment by symroe** [comment]
Yep, exactly!

On Thu, Feb 19, 2015 at 2:38 PM, Anna Powell-Smith <notifications@github.com
> wrote:

> ah thanks for the explanation... so will you redirect electionleaflets.org
> to electionleaflet.org at some point?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/electionleaflets/electionleaflets/issues/23#issuecomment-75061809>
> .
>



-- 
E: sym.roe@talusdesign.co.uk
M: 07742079314
@symroe

**Comment by annapowellsmith** [comment]
Yay!
